const ERROR_MESSAGE = {
  ERROR: "Có lỗi xảy ra!",
  ERROR_TOKEN: "Vui lòng đăng xuất và đăng nhập lại!",
  ERROR_TOKEN_TIMEOUT: "Hết thời gian chờ xin vui lòng và đăng nhập lại!",
  NOT_FOUND_TOKEN: "Thông tin đăng nhập không hợp lệ",
  NOT_FOUND_USER_INFO: "Không tìm thấy thông tin người dùng",
  LOGIN_ACCOUNT_BLOCK: "Tài khoản bị khóa.",
  REQUIRED_PARAMS: "Thiếu tham số",
  NOT_FOUND_ACCOUNT: "Không tìm thấy tài khoản",
  LOGIN_INCORRECT_PASSWORD: "Tài khoản hoặc mật khẩu không chính xác",
  NOT_FOUND_ROLE: "Không tìm thấy vai trò",
  ROLE_EXISTS: "Vai trò đã tồn tại",
  NOT_FOUND_PERMISSION: "Không tìm thấy quyền",
  PERMISSION_EXISTS: "Quyền đã tồn tại",
  NOT_FOUND_GROUP_PERMISSION: "Không tìm thấy nhóm quyền",
  GROUP_PERMISSION_EXISTS: "Nhóm quyền đã tồn tại",
  NOT_FOUND_KHOA: "Không tìm thấy khoa/phòng",
  KHOA_EXISTS: "Khoa/phòng đã tồn tại",
  NOT_FOUND_VITRI_TYPE: "Không tìm thấy loại vị trí",
  VITRI_TYPE_EXISTS: "Loại vị trí đã tồn tại",
  NOT_FOUND_CHECKLIST_ITEM: "Không tìm thấy tiêu chí",
  NOT_FOUND_VITRI_CHI_TIET: "Không tìm thấy vị trí chi tiết",
  VITRI_CHI_TIET_EXISTS: "Vị trí chi tiết này đã tồn tại trong khoa/loại vị trí đã chọn",
  NOT_FOUND_DANH_GIA: "Không tìm thấy phiếu đánh giá",
  NOT_FOUND_KHAC_PHUC: "Không tìm thấy việc khắc phục",
  NOT_FOUND_PHOTO_GALLERY: "Không tìm thấy ảnh",
  NOT_FOUND_LICH_PHAN_CONG: "Không tìm thấy lịch phân công",
  NOT_FOUND_ANH_5S_TUAN: "Không tìm thấy dữ liệu ảnh 5S tuần",
  EMAIL_EXIST: "Email đã tồn tại",
  REGISTER_EXIST_MOBILE: "Số điện thoại đã tồn tại",
  REGISTER_INVALID_MOBILE: "Số điện thoại đăng ký không hợp lệ",
  REGISTER_EXIST_EMAIL: "Email đăng ký không hợp lệ",
  DATA_NOT_FOUND: "Không tìm thấy dữ liệu",
  NOT_ACTIVE_ACCOUNT: "Tài khoản chưa hoạt động!",
  ERROR_PAYMENT: "Có lỗi xảy ra khi thanh toán!",
  VOUCHER_EXIST: 'Mã voucher đã tồn tại. Vui lòng nhập mã khác!',
  INVALID_CREATE_CATEGORY: 'Danh mục đã tồn tại',
  FORBIDDEN: 'Bạn không có quyền thao tác với dữ liệu của khoa/phòng khác',
};

module.exports = {
  ERROR_MESSAGE,
};
